[package]
name = "fluvio-extractors"
version = "0.1.0"
edition = "2018"

[dependencies]
thiserror = "1"
eyre = "0.6"
bytes = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
fluvio-dataplane-protocol = { version = "0.8", path = "../fluvio-dataplane-protocol" }
